### ISSUE TITLE
Be able to set strokeWidth

### ISSUE THREAD

**Issue by jancbeck** [themesberg/flowbite-react-icons#7]
First: awesome package! 💪🏼
Currently it looks like `strokeWidth` can be set on the icon component or via provider and is applied to the icon's SVG element. However, since `stroke-width="2"` is on every icon's `<path>` throughout the package, this does not affect rendering. 

In my naive test, adding `stroke-width="3"` to `<path>`in Chrome Dev Tools changed the stroke width as expected.

In case it's not clear what I mean, Lucide React does this well: https://lucide.dev/guide/basics/stroke-width

**Comment by SutuSebastian** [comment]
Thanks for the awesomeness!

Funny fact, I was actually thinking if this should be introduced in the first place or at a later point if there is a need for it. Well now that I see someone asked for it, I might go ahead and give it a shot.

**Comment by jancbeck** [comment]
That would be much appreciated!

**Comment by jancbeck** [comment]
@SutuSebastian any update on this one? I'm currently working on something where I would need it. If it's not too much effort, I could perhaps also submit a PR if you walk me through the key steps.

**Comment by SutuSebastian** [comment]
@jancbeck feel free to jump into the code if u want, but I have it planned the upcoming week to see if i can deliver it

**Comment by jancbeck** [comment]
Looking forward to it

**Comment by SutuSebastian** [comment]
Fixed in [v1.0.8](https://github.com/themesberg/flowbite-react-icons/releases/tag/v1.0.8).
